config/routes.rb
BobCMS::Application.routes.draw do
  root 'home#index'
  devise_for :users

  
  resources :pages, only: [:show]
  

  namespace :admin do
    resources :users, only: [:edit,:update]
    resources :dashboard, only: [:index]
    resources :layouts
    resources :pages
    resources :stylesheets
    resources :scripts
  end

  get '/admin', to: 'admin/dashboard#index', as: 'admin'
  get '/home/index', to: 'home#index'
  get '/:id', to: 'client/pages#show', as: 'client_page', :constraints => { :subdomain => /.+/ }  
  get '/stylesheets/:id', to: 'client/stylesheets#show', as: 'client_stylesheets'
  get '/javascripts/:id', to: 'client/scripts#show', as: 'client_scripts'

end

app/views/admin/pages/_form.html.erb
<div class="panel panel-default clearfix">
  <div class="panel-heading"><%= t('general').upcase%></div>
  <div class="panel-body">
    <%= form_for [:admin, page], html: {role: "form"} do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :slug %>
        <%= f.text_field :slug, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control", rows: 10 %>
      </div>
      <div class="form-group">
        <%= f.label :status %>
        <%= f.select :status, Admin::PagesController::STATUS, {},{class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.label :layout %>
        <%= f.select :layout_id, current_user.layouts.scope_main.map{|l| [l.name, l.id]}, {},{class: "form-control"} %>
      </div>
      <div class="form-group text-right">
        <%= f.submit t('submit').upcase, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div> 
<% unless page.new_record? %>
  <% unless page.is_homepage %>
    <%= form_for [:admin, page], html: {role: "form"} do |f| %>
      <%= f.hidden_field :is_homepage, value: true%>
      <div class="form-group text-right">
        <%= f.submit t('set_as_homepage').upcase, class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
  <div class="panel panel-default clearfix">
    <div class="panel-heading"><%= t('seo').upcase%></div>
    <div class="panel-body">
      <%= form_for [:admin, page], html: {role: "form"} do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :seo_title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :seo_description, class: "form-control", rows: 5 %>
        </div>
        <div class="form-group">
          <%= f.label :keywords %>
          <%= f.text_area :seo_keywords, class: "form-control", rows: 5 %>
        </div>
        <div class="form-group">
          <%= f.label :noindex %>
          <%= f.check_box :seo_noindex, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :nofollow %>
          <%= f.check_box :seo_nofollow, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :canonical %>
          <%= f.text_field :seo_canonical, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :link_prev %>
          <%= f.text_field :seo_prev, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :link_next %>
          <%= f.text_field :seo_next, class: "form-control" %>
        </div>
        <div class="form-group text-right">
          <%= f.submit t('submit').upcase, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>   
<% end %>

app/views/admin/pages/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: "form", locals: {page: @page} %>
  </div>
  <div class="col-xs-12">
    <%= render partial: "admin/stylesheets/index", locals: {resource: @page} %>
  </div>
  <div class="col-xs-12">
    <%= render partial: "admin/scripts/index", locals: {resource: @page} %>
  </div>
</div>

app/views/admin/pages/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= t('pages').upcase%></div>
  <div class="panel-body">   
    <% if current_user.layouts.present? %>       
    <div class="row">
      <div class="col-xs-12">
        <div class="pull-right">
          <%= link_to new_admin_page_path, class: "btn btn-primary", role: "button"  do %>
            <span class="glyphicon glyphicon-plus"></span> <%= t('new_page') %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Title</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @pages.each do |page| %>
              <tr>
                <td><%= page.id %></td>
                <td><%= page.title %></td>
                <td><%= page.status %></td>
                <td class="actions">
                  <%= link_to page_link(page), target: '_blank' do %>
                    <span class="glyphicon glyphicon-search">
                  <% end %>
                  <%= link_to edit_admin_page_path(page) do %>
                    <span class="glyphicon glyphicon-edit">
                  <% end %>
                  <%= link_to admin_page_path(page), method: "delete" do %>
                    <span class="glyphicon glyphicon-trash">
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% else %>
    <p>
      <%= "#{t('at_least_one_layout')}" %> <%= link_to t('create_one_now'), new_admin_layout_path %>
    </p>
  <% end %>
  </div>
</div>

app/views/admin/pages/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: "form", locals: {page: @page} %>
  </div>
</div>