config/routes.rb
BobCMS::Application.routes.draw do
  root 'home#index'
  devise_for :users

  
  resources :pages, only: [:show]
  

  namespace :admin do
    resources :users, only: [:edit,:update]
    resources :dashboard, only: [:index]
    resources :layouts
    resources :pages
    resources :stylesheets
    resources :scripts
  end

  get '/admin', to: 'admin/dashboard#index', as: 'admin'
  get '/home/index', to: 'home#index'
  get '/:id', to: 'client/pages#show', as: 'client_page', :constraints => { :subdomain => /.+/ }  
  get '/stylesheets/:id', to: 'client/stylesheets#show', as: 'client_stylesheets'
  get '/javascripts/:id', to: 'client/scripts#show', as: 'client_scripts'

end

app/models/stylesheet.rb
class Stylesheet < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => {scope: :user}
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :presence => true, :uniqueness => true
  validates :domain, :uniqueness => true, :allow_nil => true, :allow_blank => true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pages
  has_many :layouts
  has_many :stylesheets
  has_many :scripts

  def is_premium?
    package_id == 999
  end

  def homepage
    pages.published.find_by_is_homepage(true)
  end

  def usable_liquid_variable
    hash = {}
    partial_layouts.each do |partial_layout|
      hash.merge!(partial_layout)
    end
    return hash
  end
  
  def partial_layouts
    array = []
    array = layouts.scope_partial.scope_partial.map{ |l| {"partial_"+l.name => l.content}}
  end

end

app/controllers/admin/stylesheets_controller.rb
class Admin::StylesheetsController < Admin::BaseController 
  before_filter :get_stylesheet, only: [:edit,:update,:destroy]
  before_filter :set_active_sidebar
  before_filter :flash_success, only: [:create,:update,:destroy]

  before_filter :only => [:update, :destroy] do |controller|
    controller.instance_eval do
      authorize(@stylesheet)
    end
  end
  
  def set_active_sidebar
    @active_sidebar = :css  
  end

  def index
    @stylesheets = current_user.stylesheets
  end

  def new
    @stylesheet = current_user.stylesheets.new
    parent_breadcrumb
    add_breadcrumb "New", :new_admin_stylesheet_path
  end

  def create
    @stylesheet = current_user.stylesheets.new stylesheet_params
    if @stylesheet.save
      redirect_to edit_admin_stylesheet_path(@stylesheet)
    else
      flash_errors(@stylesheet)
      render "new"
    end
  end

  def edit
    parent_breadcrumb
    add_breadcrumb "#{@stylesheet.name}", edit_admin_stylesheet_path(@stylesheet)
  end

  def update
    if @stylesheet.update_attributes stylesheet_params
      redirect_to edit_admin_stylesheet_path(@stylesheet)
    else
      flash_errors(@stylesheet)
      render "new"
    end
  end

  def destroy
    @stylesheet.delete
    redirect_to admin_stylesheets_path
  end

  private

    def stylesheet_params
      params.require(:stylesheet).permit!
    end

    def get_stylesheet
      @stylesheet = Stylesheet.find params[:id]
    end

    def parent_breadcrumb
      add_breadcrumb "Stylesheets", admin_stylesheets_path
    end
end

app/controllers/client/stylesheets_controller.rb
class Client::StylesheetsController < Client::BaseController
  skip_filter :get_current_client
  skip_filter :get_current_page
  skip_filter :get_layout

  def show
    @stylesheet = Stylesheet.find params[:id]
    respond_to do |format|
      format.css {}
    end
  end
end

app/helpers/admin/stylesheets_helper.rb
module Admin::StylesheetsHelper
end

app/helpers/client/stylesheets_helper.rb
module Client::StylesheetsHelper
end

app/views/admin/stylesheets/_form.html.erb
<div class="panel panel-default clearfix">
  <div class="panel-heading"><%= t('general').upcase%></div>
  <div class="panel-body">
    <%= form_for [:admin, stylesheet], html: {role: "form"} do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :cdn_link %>
        <%= f.text_field :cdn_link, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control", rows: 10 %>
      </div>
      <div class="form-group text-right">
        <%= f.submit t('submit').upcase, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/stylesheets/_index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= t('stylesheets').upcase%></div>
  <div class="panel-body">          
    <div class="row">
      <div class="col-xs-12">
        <%= form_for [:admin, resource], html: {role: "form"} do |f| %>
        <%= f.hidden_field :stylesheet_update, value: true %>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Name</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% ids = resource.resource_stylesheets.map(&:stylesheet_id)%>
            <% current_user.stylesheets.each do |stylesheet| %>
              <tr>
                <td><%= check_box(resource.class.name.downcase, "stylesheet_ids", {:multiple => true, checked: ids.include?(stylesheet.id)}, stylesheet.id, nil) %></td>
                <td><%= stylesheet.name %></td>
                <td class="actions">
                  <%= link_to edit_admin_stylesheet_path(stylesheet) do %>
                    <span class="glyphicon glyphicon-edit">
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="form-group text-right">
          <%= f.submit t('submit').upcase, class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/stylesheets/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: "form", locals: {stylesheet: @stylesheet} %>
  </div>
</div>

app/views/admin/stylesheets/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= t('stylesheets').upcase%></div>
  <div class="panel-body">          
    <div class="row">
      <div class="col-xs-12">
        <div class="pull-right">
          <%= link_to new_admin_stylesheet_path, class: "btn btn-primary", role: "button"  do %>
            <span class="glyphicon glyphicon-plus"></span> <%= t('new_stylesheet') %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @stylesheets.each do |stylesheet| %>
              <tr>
                <td><%= stylesheet.id %></td>
                <td><%= stylesheet.name %></td>
                <td class="actions">
                  <%= link_to edit_admin_stylesheet_path(stylesheet) do %>
                    <span class="glyphicon glyphicon-edit">
                  <% end %>
                  <%= link_to admin_stylesheet_path(stylesheet), method: "delete" do %>
                    <span class="glyphicon glyphicon-trash">
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/stylesheets/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: "form", locals: {stylesheet: @stylesheet} %>
  </div>
</div>