config/routes.rb
BobCMS::Application.routes.draw do
  root 'home#index'
  devise_for :users

  
  resources :pages, only: [:show]
  

  namespace :admin do
    resources :users, only: [:edit,:update]
    resources :dashboard, only: [:index]
    resources :layouts
    resources :pages
    resources :stylesheets
    resources :scripts
  end

  get '/admin', to: 'admin/dashboard#index', as: 'admin'
  get '/home/index', to: 'home#index'
  get '/:id', to: 'client/pages#show', as: 'client_page', :constraints => { :subdomain => /.+/ }  
  get '/stylesheets/:id', to: 'client/stylesheets#show', as: 'client_stylesheets'
  get '/javascripts/:id', to: 'client/scripts#show', as: 'client_scripts'

end

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <% case msg %>
  <% when "Welcome! You have signed up successfully." %>
    <%= content_tag :div, class: "alert alert-success" do %>
      <%= content_tag :div, msg, class: "container"%>
    <% end %>
  <% when "Signed in successfully." %>
    <%= content_tag :div, class: "alert alert-success" do %>
      <%= content_tag :div, msg, class: "container"%>
    <% end %>
  <% when "Signed out successfully." %>
    <%= content_tag :div, class: "alert alert-success" do %>
      <%= content_tag :div, msg, class: "container"%>
    <% end %>
  <% when "Invalid email or password." %>
    <%= content_tag :div, class: "alert alert-danger" do %>
      <%= content_tag :div, msg, class: "container"%>
    <% end %>
  <% when "You need to sign in or sign up before continuing." %>
    <%= content_tag :div, class: "alert alert-danger" do %>
      <%= content_tag :div, msg, class: "container"%>
    <% end %>
  <% else %>
    <%= content_tag :div, class: name do %>
      <%= content_tag :div, msg, class: "container"%>
    <% end %>
  <% end %>
<% end %>
<% if (@user.errors.present? if @user.present?) %>
  <%= content_tag :div, class: "alert alert-danger" do %>
    <%= content_tag :div, class: "container" do %>
      <% @user.errors.full_messages.each do |error| %>
        <%= content_tag :li, error, style: "list-style: none;" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
_footer.html.erb

app/views/shared/_head.html.erb
<%= display_meta_tags :site => 'Bob-CMS' %>
<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bob-CMS</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li><%= link_to "Admin", admin_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
      </div>
    </div>
  </div><!-- /.container-fluid -->
</nav>