config/routes.rb
BobCMS::Application.routes.draw do
  root 'home#index'
  devise_for :users

  
  resources :pages, only: [:show]
  

  namespace :admin do
    resources :users, only: [:edit,:update]
    resources :dashboard, only: [:index]
    resources :layouts
    resources :pages
    resources :stylesheets
    resources :scripts
  end

  get '/admin', to: 'admin/dashboard#index', as: 'admin'
  get '/home/index', to: 'home#index'
  get '/:id', to: 'client/pages#show', as: 'client_page', :constraints => { :subdomain => /.+/ }  
  get '/stylesheets/:id', to: 'client/stylesheets#show', as: 'client_stylesheets'
  get '/javascripts/:id', to: 'client/scripts#show', as: 'client_scripts'

end

app/models/script.rb
class Script < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => {scope: :user}
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :presence => true, :uniqueness => true
  validates :domain, :uniqueness => true, :allow_nil => true, :allow_blank => true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pages
  has_many :layouts
  has_many :stylesheets
  has_many :scripts

  def is_premium?
    package_id == 999
  end

  def homepage
    pages.published.find_by_is_homepage(true)
  end

  def usable_liquid_variable
    hash = {}
    partial_layouts.each do |partial_layout|
      hash.merge!(partial_layout)
    end
    return hash
  end
  
  def partial_layouts
    array = []
    array = layouts.scope_partial.scope_partial.map{ |l| {"partial_"+l.name => l.content}}
  end

end

app/controllers/admin/scripts_controller.rb
class Admin::ScriptsController < Admin::BaseController
  before_filter :get_script, only: [:edit,:update,:destroy]
  before_filter :set_active_sidebar
  before_filter :flash_success, only: [:create,:update,:destroy]

  before_filter :only => [:update, :destroy] do |controller|
    controller.instance_eval do
      authorize(@script)
    end
  end
  
  def set_active_sidebar
    @active_sidebar = :javascript  
  end

  def index
    @scripts = current_user.scripts
  end

  def new
    @script = current_user.scripts.new
    parent_breadcrumb
    add_breadcrumb "New", :new_admin_script_path
  end

  def create
    @script = current_user.scripts.new script_params

    if @script.save
      redirect_to edit_admin_script_path(@script)
    else
      flash_errors(@script)
      render "new"
    end
  end

  def edit
    parent_breadcrumb
    add_breadcrumb "#{@script.name}", edit_admin_script_path(@script)
  end

  def update
    if @script.update_attributes script_params
      redirect_to edit_admin_script_path(@script)
    else
      flash_errors(@script)
      render "new"
    end
  end

  def destroy
    @script.delete
    redirect_to admin_scripts_path
  end

  private

    def script_params
      params.require(:script).permit!
    end

    def get_script
      @script = Script.find params[:id]
    end

    def parent_breadcrumb
      add_breadcrumb "Script", admin_scripts_path
    end

end

app/controllers/client/scripts_controller.rb
class Client::ScriptsController < Client::BaseController
  skip_filter :get_current_client
  skip_filter :get_current_page
  skip_filter :get_layout

  def show
    @script = Script.find params[:id]
    respond_to do |format|
      format.js {}
    end
  end
end

app/helpers/admin/scripts_helper.rb
module Admin::ScriptsHelper
end

app/helpers/client/scripts_helper.rb
module Client::ScriptsHelper
end

app/views/admin/scripts/_form.html.erb
<div class="panel panel-default clearfix">
  <div class="panel-heading"><%= t('general').upcase%></div>
  <div class="panel-body">
    <%= form_for [:admin, script], html: {role: "form"} do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :cdn_link %>
        <%= f.text_field :cdn_link, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control", rows: 10 %>
      </div>
      <div class="form-group text-right">
        <%= f.submit t('submit').upcase, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/scripts/_index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= t('scripts').upcase%></div>
  <div class="panel-body">          
    <div class="row">
      <div class="col-xs-12">
        <%= form_for [:admin, resource], html: {role: "form"} do |f| %>
        <%= f.hidden_field :script_update, value: true %>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Name</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% ids = resource.resource_scripts.map(&:script_id)%>
            <% current_user.scripts.each do |script| %>
              <tr>
                <td><%= check_box(resource.class.name.downcase, "script_ids", {:multiple => true, checked: ids.include?(script.id)}, script.id, nil) %></td>
                <td><%= script.name %></td>
                <td class="actions">
                  <%= link_to edit_admin_script_path(script) do %>
                    <span class="glyphicon glyphicon-edit">
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="form-group text-right">
          <%= f.submit t('submit').upcase, class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/scripts/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: "form", locals: {script: @script} %>
  </div>
</div>

app/views/admin/scripts/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= t('scripts').upcase%></div>
  <div class="panel-body">          
    <div class="row">
      <div class="col-xs-12">
        <div class="pull-right">
          <%= link_to new_admin_script_path, class: "btn btn-primary", role: "button" do %>
            <span class="glyphicon glyphicon-plus"></span> <%= t('new_script') %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @scripts.each do |script| %>
              <tr>
                <td><%= script.id %></td>
                <td><%= script.name %></td>
                <td class="actions">
                  <%= link_to edit_admin_script_path(script) do %>
                    <span class="glyphicon glyphicon-edit">
                  <% end %>
                  <%= link_to admin_script_path(script), method: "delete" do %>
                    <span class="glyphicon glyphicon-trash">
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/scripts/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: "form", locals: {script: @script} %>
  </div>
</div>